import { Outfit, Inter } from "next/font/google";
import "./globals.css";
import Preloader from "@/components/Preloader";

// Font configs
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// Optional metadata for Next.js (keep as is)
export const metadata = {
  title: "Raj Watches — Premium Timepieces",
  description: "Discover premium watches from top brands like Titan, Casio, Tommy Hilfiger, and more. Trusted since the 1990s for authentic, high-quality timepieces.",
};

/**
 * CartProvider using localStorage for simplicity. 
 * For advanced use, switch to Context API or Redux.
 */
function CartProvider({ children }) {
  // You can expand this later to use React Context!
  return <>{children}</>;
}

import SmoothScrolling from "@/components/SmoothScrolling";
import LoadingScreen from "@/components/LoadingScreen";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${inter.variable} antialiased`}>
        <Preloader />
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Raj Watches",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
